/'
  @title        PATRÓN FÁBRICA ABSTRACTA
  @description  El patrón Fábrica Abstracta proporciona una interfaz para crear
                familias de objetos relacionados o dependientes sin especificar
                sus clases concretas.
  @author       Gerardo Tordoya
  @date         2022-09-28
  @source       https://youtu.be/10xMzsv_yBQ
'/

@startuml Samples

' Configuración de la plantilla
skin rose
skinparam classFontName Calibri
skinparam shadowing false
' .............................

title Gerardo Tordoya

' ─── DIAGRAMA ─────────────────────────────────────────────────────────────────
Alpha -> Bravo: Mensaje enviado
Bravo -> Charlie: Mensaje reenviado
Charlie --> Alpha: Mensaje recibido
' ..............................................................................

caption www.planttext.com

@enduml
