@startuml

' Explicación: El diagrama de actividad muestra las acciones y decisiones que se
' toman durante el caso de uso "Cargar Viaje". Comienza con la carga del viaje y
' verifica si la tarjeta es de nivel oro. Si es así, se duplican las millas del
' viaje. Luego, se calculan las millas base y se verifica si el viaje supera las
' 10,000 millas. En ese caso, se suman millas adicionales para la tarjeta plata
' y, si el viaje es dentro del país, se suman millas adicionales para la tarjeta
' oro. Finalmente, se actualizan las millas acumuladas, el nivel de la tarjeta y
' se muestra una confirmación de carga exitosa.

start

:Iniciar Carga Viaje;
if (¿Es tarjeta de Nivel Oro?) then (Sí)
  :Duplicar millas;
else (No)
endif

:Calcular millas base;
if (Viaje de más de 10,000 millas?) then (Sí)
  :Sumar millas adicionales para tarjeta plata;
  if (Viaje dentro del país?) then (Sí)
    :Sumar millas adicionales para tarjeta oro;
  endif
endif

:Actualizar millas acumuladas;
:Actualizar nivel de tarjeta;
:Mostrar confirmación de carga exitosa;

stop

@enduml
