@startsalt Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Brackets (no tengo idea a qué se refiere)

{
Name:        | "    Gerardo Tordoya    "
Direction:   | { (X) Left | () Right | () Up | () Down }
Attending?:  | {  [] Yes | [] No  
                  [] Maybe }
 [Browse...]
}

@endsalt