@startsalt Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Vista de Árbol

{
    {T
     + Food
        ++ Fruit
            +++ Grape
            +++ Orange
            +++ Apple
                ++++ Honey Crisp
                ++++ Granny Smith
            +++ Banana
        ++ Vegetables
            +++ Bell pepper
            +++ Spinach
            +++ Mushroom
                ++++ Crimini
                ++++ Shitaki
    }
}

@endsalt