@startuml Samples

skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Estado Simple

[*] --> GlassEmpty
GlassEmpty --> [*]
GlassEmpty : Contents - void

GlassEmpty -> GlassFull
GlassFull : Water
GlassFull --> [*]

note right
this is a note
end note

@enduml