@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Listas en PlantUML

object Gerardo {
    * Bullet list
    * Second item
}

'Sigue la forma de hacerlo de Markdown.
note left
    * Bullet list
    * Second item
    ** Sub item
end note

'Interesante...
legend
    # Numbered list
    # Second item
    ## Sub item
    ## Another sub item
    # Third item
end legend

@enduml