@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

Alfa -> Beta : Envío --mensaje--

... Alguna ~~gran demora~~ ...

Beta -> Alfa : Recibido

note left
    This is **bold**
    This is //italics//
    This is ""monospaced""
    This is --stroked--
    This is __underlined__
    This is ~~waved~~
end note

@enduml