@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Agrupamiento y Color

nwdiag {
    internet [ shape = cloud];
    internet -- router;
    
    group {
        color = "pink";
        webserver;
        database;
    }
    
    network DMZ {
        address = "45.x.x.x/24"
        router
        webserver [address = "45.x.x.1, 45.x.x.2"];
    
    }
    network Interna {
        address = "192.x.x.x/24"
        router
        database [address = "192.x.x.1"];
        Marte [address = "192.x.x.2"];
    }
}

@enduml