@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Dos Niveles

nwdiag {

    network DMZ {
        address = "45.x.x.x/24"
        webserver [address = "45.x.x.1"];
    }

    network Interna {
        address = "192.x.x.x/24"
        webserver [address = "45.x.x.1"];
        Venus [address = "192.x.x.1"];
        Marte [address = "192.x.x.2"];
    }

}

@enduml