@startuml Samples

    ' ================================= TWEAKS =================================
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false
    ' --------------------------------------------------------------------------

    title Components - Component Diagram

    [Business Logic]
    [Data Access] as DA  
    component [Graphic User\nInterface] as GUI
    
@enduml