' =======================================
' Author:      Gerardo Tordoya
' Create date: 2022-11-02
' Description: Arquitectura UAI (7 Capas)
' =======================================

@startuml Gestor de Campeonatos

' ─── CONFIGURACIONES ──────────────────────────────────────────────────────────

' skin rose
' skinparam classFontName Calibri
' skinparam shadowing false
' hide circle
skinparam linetype ortho

' --- TÍTULO ───────────────────────────────────────────────────────────────────

title Arquitectura UAI (7 Capas)

' ─── ENTIDADES ────────────────────────────────────────────────────────────────

package BEL <<Rectangle>>
{
    class PremioModel
    {
        - int id
        - string nombre
        - string descripcion
        - int puntos
    }
}

package UIL <<Rectangle>>
{
    class PremioView
    {
        - int id
        - string nombre
        - string descripcion
        - int puntos
    }
}

package BLL <<Rectangle>>
{
    class PremioLogic
    {
        + Alta(PremioModel premio)
        + Baja(PremioModel premio)
        + Modificacion(PremioModel premio)
    }
}

package MPP <<Rectangle>>
{
    class PremioMapper
    {
        + Create(PremioModel premio)
        + Read(PremioModel premio)
        + Update(PremioModel premio)
        + Delete(PremioModel premio)
    }
}

package DAL <<Rectangle>>
{
    class PremioDAL
    {
        + Leer()
        + Escribir()
    }
    
}

package ABS <<Rectangle>>
{
    interface IEntidad
    {
        int id
    }
    interface IGestor
    {
        Alta(IEntidad entidad)
        Baja(IEntidad entidad)
        Modificacion(IEntidad entidad)
    }
}

package DAT <<Database>>
{
    annotation Premios_GetAll
    {
        @SELECT * FROM Premios
    }
}

' ─── RELACIONES ───────────────────────────────────────────────────────────────

BLL -[plain]-> MPP
DAL -[plain]-> DAT
MPP -[plain]-> DAL
UIL -[plain]-> BLL

BLL -[plain]-> BEL
MPP -[plain]-> BEL
UIL -[plain]-> BEL

BEL -[plain]-> ABS
BLL -[plain]-> ABS
MPP -[plain]-> ABS

' ─── NOTAS ────────────────────────────────────────────────────────────────────


' ─── SUBTÍTULO ────────────────────────────────────────────────────────────────

caption Última actualización: 2022-11-28

' ─── FIN ──────────────────────────────────────────────────────────────────────
@enduml