@startuml Samples
skin rose
skinparam classFontName Calibri
skinparam shadowing false

title Participantes

actor User
boundary "Web GUI" as GUI
control "Shopping Cart" as SC
entity Widget
database Widgets

@enduml