/'
  @title        PATRÓN FÁBRICA ABSTRACTA
  @description  El patrón Fábrica Abstracta proporciona una interfaz para crear
                familias de objetos relacionados o dependientes sin especificar
                sus clases concretas.
  @author       Gerardo Tordoya
  @date         2022-09-28
  @credits      https://youtu.be/10xMzsv_yBQ
'/

@startuml Nicosio

' Configuración de la plantilla (skin clásico, fuente Excel, sin sombras).
skin rose
skinparam classFontName Calibri
skinparam shadowing false

' Inicio del diagrama.
title Fábrica Abstracta


' ─── OBJETOS ──────────────────────────────────────────────────────────────────
class Cliente

interface IFabricaAbstracta
class FabricaA
class FabricaB

interface IProductoAbstracto1
class Producto1A
class Producto1B

interface IProductoAbstracto2
class Producto2A
class Producto2B


' ─── RELACIONES ───────────────────────────────────────────────────────────────
Cliente o-- IFabricaAbstracta
Cliente o-- IProductoAbstracto1
Cliente o-- IProductoAbstracto2

IFabricaAbstracta <|.. FabricaA
IFabricaAbstracta <|.. FabricaB

IProductoAbstracto1 <|.. Producto1A
IProductoAbstracto1 <|.. Producto1B

IProductoAbstracto2 <|.. Producto2A
IProductoAbstracto2 <|.. Producto2B

FabricaA ..> Producto1A
FabricaA ..> Producto2A

FabricaB ..> Producto1B
FabricaB ..> Producto2B


' Fin del diagrama.
caption https://youtu.be/10xMzsv_yBQ

@enduml
