@startuml Samples

    ' ================================= TWEAKS =================================
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false
    ' --------------------------------------------------------------------------

    title Interfaces - Class Diagram

    class Car
    ICar1 ()- Car
    ICar2 ()-- Car
    Car -() ICar3
    
@enduml