@startuml Prinzo

class Vehículo {
  - tipo: string
  - marca: string
  - modelo: string
  - patente: string
}

class Cliente {
  - nombre: string
  - apellido: string
  - dni: int
  - nacimiento: date
  - email: string
}

class Renta {
  - vehículo: Vehículo
  - cliente: Cliente
  - cantidad: int
  - importe: decimal
}

Vehículo --> Cliente
Cliente --* Renta

@enduml
