@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Diagrama by Gerardo Tordoya
'====================================

@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Paquete
'====================================

rectangle Features {
    (Login)
    (Create / Delete User) as CDU
}

:Employee: 
:Client:
:Supervisor:

Employee --> (Login)
Supervisor --> (Login)
Client ..> (Login) : NO!!!!
Supervisor ---> CDU: I am god

@enduml