@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Diagrama by Gerardo Tordoya
'====================================

@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Estereotipos
'====================================

(Upload File) as UF<<Manual>>
actor :User: as U<<Person>>
:HAL: as H<<Computer>>

U -> UF
U ---> (L)
H <.up.> (L)

@enduml