@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Diagrama by Gerardo Tordoya
'====================================

@startuml Samples
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false

    title Actores
'====================================

:Administrator:
:Standard User: as SU  
actor Accountant
actor :Client: as C

@enduml