@startuml Arquitectura 7UP

' ================================================================
' Author:       Gerardo Tordoya
' Create date:  2023-03-30
' Description:  Arquitectura 7UP (basada en Arquitectura Cardacci)
' ================================================================


' --- CONFIGURACION DEL DIAGRAMA (Tipo: Diagrama de Clases) --------------------

' skin rose
' skinparam classFontName Calibri
' skinparam shadowing false
' hide circle
skinparam linetype ortho


' --- TITULO DEL DIAGRAMA ------------------------------------------------------

title Arquitectura 7UP


' --- ENTIDADES ----------------------------------------------------------------

package View <<Rectangle>> {
}


package Presenter <<Rectangle>> {
}

' note right of Presenter
'     Controladora
'     de la GUI
' end note

package Model <<Rectangle>> {
}

' note bottom of Model
'     Business Entities (BE)
'     Estructura (Cardacci)
' end note

package Abstract <<Rectangle>> {
}


package Logic <<Rectangle>> {
}


package Mapper <<Rectangle>> {
}


package DataAccess <<Rectangle>> {
}


package Database <<Database>> {
}


' --- RELACIONES ---------------------------------------------------------------

View       --> Abstract
Presenter   -> Abstract
Model     ---> Abstract
Logic       -> Abstract
Mapper      -> Abstract

View       --> Presenter

Presenter  --> Model
Presenter  --> Logic

Logic      --> Model
Logic      --> Mapper

Mapper     --> Model
Mapper     --> DataAccess

DataAccess --> Database


' --- PIE DE DIAGRAMA ----------------------------------------------------------

caption Copyright © 2023 Gerardo Tordoya


@enduml