@startuml Tutorial

title Casos de Uso

' =================================== TWEAKS ===================================
skin rose
skinparam classFontName Calibri
skinparam shadowing false
' ------------------------------------------------------------------------------

actor Promoter
actor Entrant

Promoter --> (Create Event)
Promoter -> (Attend Event)

Entrant --> (Find Event)
(Attend Event) <- Entrant

(Attend Event) <.. (Create Member)  : <<include>>

@enduml