@startuml Tutorial

    title Diagrama de Clases

    ' ================================= TWEAKS =================================
    skin rose
    skinparam classFontName Calibri
    skinparam shadowing false
    ' --------------------------------------------------------------------------

    interface Clase1
    {
        Contrato()
    }
 
    class Clase2
    {
        +string[] elementos
        -int contador
        +MostrarElementos()
        -Contrato()
    }

    class Clase3
    {
        'private
        -field1
        'protected
        #field2

        'package private
        ~method1()
        'public
        +method2()
        -Contrato()
    }
 
    Clase1 <|-- Clase2: Herencia
    Clase1 <|-- Clase3
    
    Clase4 "1" *-- "n" Clase5: Composición
    Clase6 o-- Clase7: Agregación

    class Car
    ICar ()-- Car
    ICar2 ()- Car
    Car -() ICar3


@enduml